// <auto-generated />
using System;
using CookingWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CookingWebsite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519102357_AddFileUpload")]
    partial class AddFileUpload
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("CookingWebsite.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalPhoto2")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalPhoto3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorAvatar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<int>("Comments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingredients")
                        .HasColumnType("TEXT");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Servings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Steps")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipIcon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoDuration")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoEmbedUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoThumbnail")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalPhoto2 = "https://images.unsplash.com/photo-1547592180-85f173990554?w=700",
                            AdditionalPhoto3 = "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=700",
                            Author = "Maria Santos",
                            AuthorAvatar = "MS",
                            Category = "Filipino",
                            Comments = 14,
                            Content = "After 3 years of trying, I finally nailed my grandmother's chicken adobo. The secret is coconut vinegar and letting it rest overnight. The flavors deepen beautifully. Every bite brings me right back to her kitchen in Cebu.",
                            CookTimeMinutes = 60,
                            DatePosted = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Medium",
                            Ingredients = "1 kg chicken thighs\n1/2 cup coconut vinegar\n1/4 cup soy sauce\n1 head garlic, crushed\n3 bay leaves\n1 tsp black peppercorns\n1 cup water",
                            Likes = 87,
                            PhotoUrl = "https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=700",
                            PrepTimeMinutes = 15,
                            Servings = 4,
                            Steps = "Combine chicken, vinegar, soy sauce, garlic, bay leaves, peppercorns, and water in a pot.\nMarinate for at least 1 hour, overnight is best.\nBring to a boil then simmer for 30 minutes covered.\nUncover and reduce sauce until it thickens and coats the chicken.\nOptional: fry chicken pieces in oil until golden before serving.",
                            Title = "My Grandma's Chicken Adobo — Finally Perfected It!",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Author = "Chef James",
                            AuthorAvatar = "CJ",
                            Comments = 22,
                            Content = "One of the most useful knife skills you can learn. Uniform cuts mean even cooking. I demonstrate on carrots, zucchini, and bell peppers. Watch till the end for the pro tip on keeping your fingers safe!",
                            DatePosted = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Likes = 134,
                            Title = "How to Julienne Vegetables Perfectly — 3-Minute Tutorial",
                            Type = 1,
                            VideoDuration = "3:24",
                            VideoEmbedUrl = "https://www.youtube.com/embed/dQw4w9WgXcQ",
                            VideoThumbnail = "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=700"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Priya Nair",
                            AuthorAvatar = "PN",
                            Comments = 31,
                            Content = "Toast dry spices in a dry pan for 30 to 60 seconds before using them. This blooming releases essential oils and dramatically deepens the flavor. Works for cumin, coriander, paprika — any whole or ground spice. A 1-minute step that makes a massive difference.",
                            DatePosted = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Likes = 203,
                            TipCategory = "Spices & Seasoning",
                            TipIcon = "🌶️",
                            Title = "Always Bloom Your Spices First",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            AdditionalPhoto2 = "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=700",
                            Author = "Elena Cruz",
                            AuthorAvatar = "EC",
                            Category = "Breakfast",
                            Comments = 9,
                            Content = "Made this for the whole family last weekend and it was gone in minutes. The trick is day-old brioche — it soaks up the custard without getting soggy. I add cream cheese and strawberry jam in the middle. Game changer for brunch!",
                            CookTimeMinutes = 45,
                            DatePosted = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Easy",
                            Ingredients = "1 loaf day-old brioche, cubed\n4 large eggs\n1.5 cups milk\n1/2 cup heavy cream\n3 tbsp maple syrup\n1 tsp vanilla extract\n200g cream cheese\n3 tbsp strawberry jam\nPowdered sugar for serving",
                            Likes = 56,
                            PhotoUrl = "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=700",
                            PrepTimeMinutes = 10,
                            Servings = 6,
                            Steps = "Grease a 9x13 baking dish. Place half the brioche cubes inside.\nMix cream cheese and jam; dollop over the bread layer.\nTop with remaining brioche cubes.\nWhisk eggs, milk, cream, maple syrup, and vanilla. Pour over bread.\nPress down gently; cover and refrigerate overnight or 1 hour.\nBake at 175C for 40-45 minutes until golden and puffed.\nDust with powdered sugar and serve with extra maple syrup.",
                            Title = "Sunday Morning French Toast Bake",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Author = "Chef Antoine",
                            AuthorAvatar = "CA",
                            Comments = 47,
                            Content = "There is nothing more satisfying than making pasta with your own hands. I walk through everything: flour ratio, kneading, resting time, and rolling. No pasta machine needed — just a rolling pin and patience.",
                            DatePosted = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Likes = 289,
                            Title = "Homemade Pasta from Scratch — Full Process",
                            Type = 1,
                            VideoDuration = "12:07",
                            VideoEmbedUrl = "https://www.youtube.com/embed/dQw4w9WgXcQ",
                            VideoThumbnail = "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=700"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Sarah Kim",
                            AuthorAvatar = "SK",
                            Comments = 19,
                            Content = "When making pie crust, biscuits, or scones, your butter must be ice cold. Warm butter melts into the flour and creates a dense texture. Cold butter creates steam pockets while baking, resulting in light, flaky layers. Cut into cubes and freeze 15 minutes before using.",
                            DatePosted = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Likes = 178,
                            TipCategory = "Baking",
                            TipIcon = "🧈",
                            Title = "Use Cold Butter for Flakier Pastry",
                            Type = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
